/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasePageContent: typeof import('./src/components/BaseLayout/BasePageContent.vue')['default']
    BaseSideMenu: typeof import('./src/components/BaseLayout/BaseSideMenu.vue')['default']
    BasicSetting: typeof import('./src/components/Setting/BasicSetting.vue')['default']
    CampaignStatChart: typeof import('./src/components/Campaign/CampaignStatChart.vue')['default']
    CustomizeDropZone: typeof import('./src/components/CustomizeDropZone.vue')['default']
    ExternalLinkTooltip: typeof import('./src/components/ExternalLinkTooltip.vue')['default']
    GameProfileChecker: typeof import('./src/components/GameProfileChecker.vue')['default']
    IconTooltip: typeof import('./src/components/IconTooltip.vue')['default']
    LastDayShortDataDisplay: typeof import('./src/components/ProjectArcade/LastDayShortDataDisplay.vue')['default']
    LobbiesCounter: typeof import('./src/components/ProjectArcade/LobbiesCounter.vue')['default']
    LocalesChanger: typeof import('./src/components/Setting/LocalesChanger.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    ProfileSetting: typeof import('./src/components/Setting/ProfileSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceLinks: typeof import('./src/components/Setting/ServiceLinks.vue')['default']
    SupportIcon: typeof import('./src/components/SupportIcon.vue')['default']
    VersionUpdater: typeof import('./src/components/Setting/VersionUpdater.vue')['default']
  }
}
